apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devdb{{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
    template:
      spec:
        containers:
        - name: devdb
          image: eu.gcr.io/mmtest-212008/devdb:latest